### ISSUE TITLE
Messages published with quality level 2 are not bradcasted

### ISSUE THREAD

**Issue by bertof** [Syndim/actix-mqtt-client#1]
Hi, I'm trying to integrate this library in a project of mine and I'm having issues with messages published on level 2.

The issue can be replicated with your example code. I'm using a Mosquitto broker in my same subnet. Messages sent on level 0 and level 1 do get sent and broadcasted but messages on level 2 seem to not be broadcasted.

If the client gets immediately disconnected as from te he example, level 2 messages are sent but not broadcasted.
On the other end, if the client is not disconnected, i.e. I replace `client.disconnect()` with a simple `Ok(())`, the message is correctly broadcasted.

There might be a race condition between the client disconnection and the completion of the message publication.

**Comment by Syndim** [comment]
@bertof Thanks for reporting! I made a change in the `wait_for_packets_before_disconnect` branch which should resolve this issue, can you try that branch and see if it works for you?

**Comment by bertof** [comment]
Hi! Sorry for the late response. It seems to work correctly now, both with the example code and in my integration. It also seem to have fixed a missing ACK error while publishing in Level2. Thank you very much!
