### ISSUE TITLE
support MQTT over websocket

### ISSUE THREAD

**Issue by xudesheng** [Syndim/actix-mqtt-client#10]
Hi, @Syndim 👍 
    so far, this lib works great. really appreciate.

    do you have plan to support MQTT over websocket?

**Comment by Syndim** [comment]
Hi @xudesheng, this library itself doesn't depend on any underlying protocol. As long as you can create something which implements `tokio::io::AsyncRead` and `tokio::io::AsyncWrite` and pass it to the client it should work out of the box.

I'm not familiar with MQTT over websocket but I did a quick search and it looks this library: https://docs.rs/tokio-tungstenite/ can create a websocket stream and maybe can be used.

**Comment by xudesheng** [comment]
> Hi @xudesheng, this library itself doesn't depend on any underlying protocol. As long as you can create something which implements `tokio::io::AsyncRead` and `tokio::io::AsyncWrite` and pass it to the client it should work out of the box.
> 
> I'm not familiar with MQTT over websocket but I did a quick search and it looks this library: https://docs.rs/tokio-tungstenite/ can create a websocket stream and maybe can be used.

Thank you! this lib looks great.
I will try to work on it when I have bandwidth.
