### ISSUE TITLE
TlsStream causes "early eof"?

### ISSUE THREAD

**Issue by braincow** [Syndim/actix-mqtt-client#11]
Using native_tls and tokio_native_tls crates in the fashion (example is simplified version of my code):

```
        let tcp_stream = TcpStream::connect(mqtt_server_sockaddr).await.unwrap();

        let inner_cx = TlsConnector::builder()
                .min_protocol_version(Some(native_tls::Protocol::Tlsv12))
                .build().unwrap();

        let outer_cx = tokio_native_tls::TlsConnector::from(inner_cx);
        let tls_stream = outer_cx.connect(mqtt_server_hostname, tcp_stream).await.unwrap();

        trace!("{:?}", tls_stream);
        let (reader, writer) = split(tls_stream);

        let client = MqttClient::new(
            reader, writer,
            "device_id",
            MqttOptions::default(),
            MessageActor.start().recipient(),
            ErrorActor.start().recipient(),
            None,
        );

        client.connect().await.unwrap();

        // Waiting for the client to be connected
        while client.is_connected().await.unwrap() {
            let delay_time = Instant::now() + Duration::new(1, 0);
            delay_until(delay_time).await;
        }
```

Always ends up with an error:

 2020-08-14T11:25:53.125Z ERROR actix_mqtt_client::actors::actions::recv        > Failed to parse packet: early eof

My guess is that splitted TlsStream is different somehow compared to the TcpStream and thus causes read/write issues in reader/writer.

Any ideas on how to properly setup the TLS connectivity if this is my mistake..?

**Comment by Syndim** [comment]
Hi, the error indicates that the parsing has failed. The parsing logic is done by the `mqtt-protocol` crate [here](https://github.com/Syndim/actix-mqtt-client/blob/2aeb1c081f89808be3475da59f6149463b558bda/src/actors/actions/recv.rs#L68). 

Can you try to pass the AsyncRead directly to `VariablePacket::parse` and see if you get the same error?

**Comment by Syndim** [comment]
Close because of no response from the reporter. Feel free to reopen it again if you still have this issue.
