### ISSUE TITLE
support tls connection on port 8883

### ISSUE THREAD

**Issue by xudesheng** [Syndim/actix-mqtt-client#6]
I'm trying to connect to Azure IoTHub, which is on port 8883 and tls is enforced.

I didn't find any option to set up CA cert for tls communication.

Could you kindly please show me a quick example?

thanks.

**Comment by Syndim** [comment]
In order to connect to TLS endpoints you will need to use rust-native-tls crate: https://github.com/sfackler/rust-native-tls

You can read its README to create the TLS stream and then split it into ReadHalf and WriteHalf and pass the the MQTT client.

**Comment by xudesheng** [comment]
> In order to connect to TLS endpoints you will need to use rust-native-tls crate: https://github.com/sfackler/rust-native-tls
> 
> You can read its README to create the TLS stream and then split it into ReadHalf and WriteHalf and pass the the MQTT client.

really appreciate!
it works by using both rust-native-tls and tokio-tls.

**Comment by Syndim** [comment]
Glad it worked! Closing this issue for now. If you have other questions feel free to open another one.
